apiVersion: v1
kind: Service
metadata:
  name: ceng459-ninth-assignment
  labels:
    app: ceng459-ninth-assignment
spec:
  type: ClusterIP
  selector:
    app: ceng459-ninth-assignment
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceng459-ninth-assignment
  labels:
    app: ceng459-ninth-assignment
spec:
  selector:
    matchLabels:
      app: ceng459-ninth-assignment
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ceng459-ninth-assignment
    spec:
      containers:
      - name: ceng459-ninth-assignment
        image: sefibra/ceng459-ninth-assignment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "2000m"

