apiVersion: v1
kind: Service
metadata:
  name: py-application-cpu
  labels:
    app: py-application-cpu
spec:
  type: ClusterIP
  selector:
    app: py-application-cpu
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-application-cpu
  labels:
    app: py-application-cpu
spec:
  selector:
    matchLabels:
      app: py-application-cpu
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: py-application-cpu
    spec:
      containers:
      - name: py-application-cpu
        image: sefibra/py-application-cpu:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "2000m"

